### PR TITLE
Add "onormal" arrow style

### PR DESCRIPTION
**Pull request by tantignac**
Proposition to add a new arrow style for edges.

### CODE REVIEW

**Comment by yakobowski** [comment]
Thanks for this contribution!

I'm torn because there are still tons of styles that are not supported (34 to be exact...). There is _some_ logic behind the naming convention, and it may be possible to support all of them using a relatively small DSL. Unfortunately, I don't see how to do this with breaking API compatibility, something we won't do just to avoid creating too many constructors. 

In the meantime, can you also add yourself to the Changelog? Thanks!

**Comment by yakobowski** [comment]
Ping :)

**Comment by backtracking** [comment]
@yakobowski OCamlGraph does not compile anymore. This commit changes type `arrow_style` in `graphviz.ml` but not in `graphviz.mli`!

**Comment by backtracking** [comment]
Fixed in commit 135afb6e17577b36c12fe71b1b198bfacf37270c

**Comment by yakobowski** [comment]
Argh! Sorry for that...

**Pull request merged**
