### PR TITLE
Dune

### PR DESCRIPTION
**Pull request by giltho**
Hi !
Sorry this is a long read, but the content is simple

## Intro

So I wanted to make some modifications to ocamlgraph (making the layout system agnostic of the rendering system somehow), and I'm very bad with makefiles so I thought porting the project to dune would be a good way to understand how the library works.

I've spent a bit more than a day trying to make the change and it has been quite interesting. In particular, some of the code is 14 years old and it looks like it had not been compiled in a while. But generally, everything seems to be working now. It is not quite finished though, since there is some cleaning to do, maybe a migration to ocamlformat...

However, I do need the opinion of a maintainer on what I did. There is a breaking change (I split ocamlgraph into two packages).

### ocamlgraph and ocamlgraph_gtk

I split ocamlgraph into two packages :

- `ocamlgraph` that exposes a toplevel `Graph` module which is basically what you would get if you installed `ocamlgraph` withtout lablgtk on your machine. 
- `ocamlgraph_gtk` that exposes a toplevel `Graph_gtk` module, which is the rest, what was the internal `dgraph` library (`XDot`, `XDotDraw`, `DGraphTreeLayout` ...)

This was done in the spirit of, for example, `cohttp` and `cohttp_lwt`. It is more aligned with the most modern OCaml practices. Also, it is not too much of a change, since it is very simple to make the migration, although it has to be done manually. Finally, it was very confusing for me to not have access to some modules of the library described in the API documentation, and it took me a while to realise (after looking at the configure file) that it was because I did not have lablgtk installed. I think it is clearer to make the dependencies explicit, and to make explicit what you get compiled, and to explicitly throw an error if it is not to possible to obtain the dgraph part of the library.

That being said, the old behaviour could be obtained using some dune-configurator magic.

**Questions**:
- [x] Do you believe this is the right direction ?

#### tests

I made the tests completely automatic. They can now all be run using
```sh
$ dune test
```

The price to make the tests automatic was to remove anything that would open a graphical interface. I think only one test did that, and it did it after printing to a file its results.
I didn't go through the trouble of using something like alcotest. Tests were either printing something that the user should manually check or using some asserts. I just ran the asserts tests and I added some snapshots of what the tests should output and let dune do its magic to check that the tests still print what's expected.

Note that it is possible to run each test individually by simply executing it. For example, it is possible to run the `check.ml` tests by running
```sh
$ dune exec tests/check.exe
```

**FIXME**:
- [ ] The `nonneg.ml` tests are not compiling, because they're using `Pack.NonnegDigraph` which I guess was removed from the library.

#### benchmarks

There is a `benchs` folder but it does not really contain anything interesting. It was last modified 14 years ago and the commit message associated is "debut de benchs incomplet" which probably means que ça n'a jamais été terminé.

There is also a `bench.ml` files that is indeed doing some heavy computations. I did not make it part of the test suite, but it can be run using either
```sh
$ dune build @bench  // will suppress the output
```
or
```sh
$ dune exec tests/bench.exe  // output will be shown
```

**Question**:
- [ ] Should the benchs folder be removed ?

### ViewGraph

The ViewGraph library, although marked as deprecated, compiles. I think it exposes the exact same interface as it used to. `viewGraph_test.ml` also compiles properly and can be run for example using 
```sh
$ dune exec view_graph/viewGraph_test.exe
```

### Examples

All examples properly compile and can be run individually using, for example
```
$ dune exec examples/demo_planar.exe
```

### editor

I don't really understand what is happening in that folder. There are 4 different executables from what I understand. Only 3 of them compile properly, but I think the last one has not been used in ages.

#### ed_graph

It compiles and can be run using
```sh
$ dune exec editor/ed_main.exe
```

#### editor

It compiles and can be run using
```sh
$ dune exec editor/editor.exe editor/tests/full20.gml // for example
```

However, there is one file that does not compile anymore (dirTree.ml) but the code that uses it is commented out.

#### graphEd and graphEdGTK

GraphEd is not compiling anymore. Some functions seems to have been removed from `outils_tort.ml`.

graphEdGTK however, compiles properly and can be run using:
```sh
$ dune exec editor/graphEdGTK.exe -- editor/tests/full20.gml
```

### dGraphViewer

It is not part of the library, it is an executable.
It compiles properly, but whenever I run it, I get a segfault from gtk.
```sh
$ dune exec dgraph/dGraphViewer.exe
```
<details>
  <summary>Unfold the terribly boring segfaulting output</summary>
  
  ```sh
  (process:19077): GLib-GObject-WARNING **: 23:59:23.455: invalid (NULL) pointer instance

  (process:19077): GLib-GObject-CRITICAL **: 23:59:23.455: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

  (process:19077): GLib-CRITICAL **: 23:59:23.456: g_hash_table_lookup: assertion 'hash_table != NULL' failed

  (process:19077): GLib-CRITICAL **: 23:59:23.456: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

  (process:19077): GLib-CRITICAL **: 23:59:23.456: g_hash_table_lookup: assertion 'hash_table != NULL' failed

  (process:19077): GLib-CRITICAL **: 23:59:23.456: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

  (process:19077): GLib-CRITICAL **: 23:59:23.456: g_hash_table_lookup: assertion 'hash_table != NULL' failed

  (process:19077): GLib-CRITICAL **: 23:59:23.456: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

  (process:19077): GLib-GObject-WARNING **: 23:59:23.456: invalid (NULL) pointer instance

  (process:19077): GLib-GObject-CRITICAL **: 23:59:23.456: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

  (process:19077): GLib-CRITICAL **: 23:59:23.457: g_hash_table_lookup: assertion 'hash_table != NULL' failed

  (process:19077): GLib-CRITICAL **: 23:59:23.457: g_hash_table_lookup: assertion 'hash_table != NULL' failed

  (process:19077): GLib-CRITICAL **: 23:59:23.457: g_hash_table_lookup: assertion 'hash_table != NULL' failed

  (process:19077): GLib-CRITICAL **: 23:59:23.457: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

  (process:19077): GLib-CRITICAL **: 23:59:23.457: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  [1]    19077 segmentation fault  dune exec dgraph/dGraphViewer.exe
  ```
  
</details>

I don't know if it means there's something wrong with the `graph_gtk` library but I have not really touched it...
I'm on mac, so probably things are not as smooth with gtk as on ubuntu + gnome.

Secondly, there's a file, `DGraphMake` that does not seem to do anything, I think it can safely be removed.

**Questions**:
- [ ] Is it normal that I get this ?
- [ ] Should DGraphMake be removed ?

### Frama-C

All of the questions above should be discussed, but in particular the one about ocamlgraph + ocamlgraph_gtk.
Moreover, I know that ocamlgraph is heavily used in Frama-C even though I did not manipulate it myself when I was interning there. I want to make sure that anything we do here doesn't prevent the frama-c team from upgrading (@signoles and @bobot ? Sorry for the noise, hope you guys are fine in these strange times :smile:)
I noticed some frama-c specific things in the Makefile but haven't got into the details of it, is there anything needed ?

### Cleaning the old Makefiles

Most of them shouldn't be needed anymore. We can keep a main Makefile with some rules that would allow one not to remember how to launch tests / benchmarks / executables / build / deploy etc... Makefile + dune happens a lot, but the Makefiles are quite simple.

Of course, the Makefiles that build something else than ocaml (papers / website / docs) should probably be kept.

### The documentation

One can easily get a nice documentation using
```
dune build @doc
```
if odoc is installed, but it is not exactly the old documentation, style is not the same.
I also haven't tried yet to build the website.
It could be good to keep both versions and maintain the old documentation for a while for people who have not upgraded ?

### Formatting

Moving from ocp-indent to ocamlformat could be good.

### CI

It would be trivial to set up github actions that automatically build and test everything that can be tested on CI (modulo maybe not trivial to build gtk on a github VM ?).

### CODE REVIEW

**Comment by backtracking** [comment]
Many thanks for this tremendous effort.
As far as I'm concerned, I'll be happy to switch to dune but, as you notice yourself, we cannot
do that without the blessing of Frama-C developers.
I'll ping @signoles.

**Comment by yakobowski** [comment]
Thanks Sacha for all this work, it is very much appreciated! I think you took all the good decisions here.

For the sake of completeness, I have to point out that merging this will lose us some compatibility with old versions of OCam: OCamlGraph probably supports older versions of the compiler than Dune does. Nevertheless, I think it is time to bite that particular bullet. Installing OCaml packages has become significantly easier thanks to Opam, so I think we can afford supporting fewer old versions. So, since we have the conditional agreement from Jean-Christophe, I will be happy to review. (Waiting for an agreement from the Frama-C team, of course.)

**Comment by giltho** [comment]
Thank you for your answer !
Since you're agreeing with the direaction, I'm gonna improve a bit things then, starting with these encoding issues that appeared

I also fixed the several times I said `ocamlformat` instead of `ocamlgraph` in the PR description, I must have been quite tired hahahaha

**Comment by yakobowski** [comment]
> Thank you for your answer !
> Since you're agreeing with the direction, I'm gonna improve a bit things then, starting with these encoding issues that appeared

Great! I was a bit puzzled.

Also, can you investigate the first version of OCaml in which `Stdlib` (including with the Opam replacement packages)? Thanks!

**Comment by giltho** [comment]
I think your message is missing a word after `Stdlib` so I don't quite know what the question is 😅

**Comment by yakobowski** [comment]
Argh! Many words in fact: `Stdlib is available`.

**Comment by giltho** [comment]
Ah makes sense
`Stdlib` has been introduced in 4.07, and `stdlib-shims` allows compatibility with versions down to 4.02.3.
`dune` needs 4.02 minimum to work, so they're both setting the same limits.

This is ok for Frama-C since the latest version uses 4.05 according to their documentation.
However, as you said, it does break compatibility with any older version. I guess this is ok, since opam will still have the old ocamlgraph versions to build old projects.

**Pull request merged**
